SUMMARY = "Open standard for machine learning interoperability"
HOMEPAGE = "https://github.com/onnx/onnx"
LICENSE = "Apache-2.0"
LIC_FILES_CHKSUM = "file://LICENSE;md5=3b83ef96387f14655fc854ddc3c6bd57"

SRC_URI = " \
    git://github.com/onnx/onnx.git;protocol=https;branch=rel-${PV};tag=v${PV} \
    file://0001-Updates-for-OE-cross-builds.patch \
    file://0002-Fix-ONNX_ML-not-applied-to-Python-bindings-on-non-M.patch \
"
SRCREV = "b8baa8446686496da4cc8fda09f2b6fe65c2a02c"

inherit cmake python3native

DEPENDS += " \
    protobuf \
    protobuf-native \
    python3-pybind11 \
"

EXTRA_OECMAKE = " \
    -DBUILD_SHARED_LIBS=ON \
    -DONNX_BUILD_TESTS=OFF \
    -DONNX_BUILD_BENCHMARKS=OFF \
    -DONNX_VERIFY_PROTO3=ON \
    -DONNX_USE_PROTOBUF_SHARED_LIBS=ON \
    -DProtobuf_LIBRARY="${STAGING_LIBDIR}/libprotobuf.so" \
    -DONNX_DISABLE_STATIC_REGISTRATION=ON \
"

PACKAGECONFIG ??= "python ml"
PACKAGECONFIG[ml] = "-DONNX_ML=1, -DONNX_ML=0"
PACKAGECONFIG[python] = " \
    -DBUILD_ONNX_PYTHON=ON \
    -DPYTHON_LIBRARY=${PYTHON_LIBRARY} \
    -DPYTHON_INCLUDE_DIRS=${PYTHON_INCLUDE_DIR}, \
    -DBUILD_ONNX_PYTHON=OFF, \
    python3-protobuf-native \
"

do_install:append() {
    # remove lines with tmpdir references, they're harmful when we build against this later
    sed -i '/CMAKE_PREFIX_PATH/d' ${D}${libdir}/cmake/ONNX/ONNXConfig.cmake
    sed -i '/Protobuf_INCLUDE_DIR/d' ${D}${libdir}/cmake/ONNX/ONNXConfig.cmake

    # Install the Python package
    CP_ARGS="-Prf --preserve=mode,timestamps --no-preserve=ownership"
    if ${@bb.utils.contains('PACKAGECONFIG', 'python', 'true', 'false', d)}; then
        install -d ${D}${PYTHON_SITEPACKAGES_DIR}/onnx
        (cd ${S}/onnx; cp --parents $(find . -name "*.py*") ${D}${PYTHON_SITEPACKAGES_DIR}/onnx)
        cp $CP_ARGS ${B}/onnx ${D}${PYTHON_SITEPACKAGES_DIR}
        cp $CP_ARGS ${B}/onnx_cpp2py_export.so ${D}${PYTHON_SITEPACKAGES_DIR}/onnx

        # Generate version.py — created by setup.py at build time but not in the source tree
        cat > ${D}${PYTHON_SITEPACKAGES_DIR}/onnx/version.py <<EOF
# This file is generated by setup.py. DO NOT EDIT!
version = "${PV}"
git_version = ""
EOF
    fi
}

PACKAGES =+ "python3-${PN}"
FILES:python3-${PN} += "${PYTHON_SITEPACKAGES_DIR}"
RDEPENDS:python3-${PN} += " \
    ${PN} \
    python3-numpy \
    python3-protobuf \
    python3-flatbuffers \
    python3-sympy \
"
