SUMMARY = "Open standard for machine learning interoperability"
HOMEPAGE = "https://github.com/onnx/onnx"
LICENSE = "Apache-2.0"
LIC_FILES_CHKSUM = "file://LICENSE;md5=3b83ef96387f14655fc854ddc3c6bd57"

DEPENDS = " \
    protobuf \
    protobuf-native \
    python3-nanobind-native \
"
DEPENDS:append:toolchain-clang = "lld-native"

SRC_URI = " \
    git://github.com/onnx/onnx.git;protocol=https;branch=rel-${PV};tag=v${PV} \
    file://0001-Fix-nanobind-cross-compile-Python-namespace-mismatch.patch \
    file://0002-Disable-nanobind-strip-on-link-for-Yocto-packaging.patch \
"
SRCREV = "d3f6b795aedb48eaecc881bf5e8f5dd6efbe25b3"

inherit cmake python3native python3targetconfig

EXTRA_OECMAKE = " \
    -DBUILD_SHARED_LIBS=ON \
    -DONNX_BUILD_TESTS=OFF \
    -DONNX_BUILD_BENCHMARKS=OFF \
    -DONNX_VERIFY_PROTO3=ON \
    -DONNX_USE_PROTOBUF_SHARED_LIBS=ON \
    -DProtobuf_LIBRARY=${STAGING_LIBDIR}/libprotobuf.so \
    -DONNX_DISABLE_STATIC_REGISTRATION=ON \
"

LDFLAGS:append:toolchain-clang = " -fuse-ld=lld"

# nanobind-config.cmake computes NB_DIR as two levels up from its own location
# (.../usr/lib/cmake/nanobind/ -> .../usr/lib/cmake), but nanobind sources live
# in site-packages/nanobind/. Symlink include/, src/, and ext/ into place so
# nanobind_build_library() finds its sources at the expected ${NB_DIR}/include
# and ${NB_DIR}/src paths without patching the cmake config.
do_configure:prepend() {
    NB_CMAKE_DIR="${RECIPE_SYSROOT_NATIVE}/usr/lib/cmake"
    NB_SRC="${RECIPE_SYSROOT_NATIVE}/usr/lib/python${PYTHON_BASEVERSION}/site-packages/nanobind"
    ln -sfn "${NB_SRC}/include" "${NB_CMAKE_DIR}/include"
    ln -sfn "${NB_SRC}/src"     "${NB_CMAKE_DIR}/src"
    ln -sfn "${NB_SRC}/ext"     "${NB_CMAKE_DIR}/ext"
}

PACKAGECONFIG ??= "python ml"
PACKAGECONFIG[ml] = "-DONNX_ML=ON,-DONNX_ML=OFF"
# v1.20.1 uses FindPython3 cmake module; pass Python3_ variants of the hints.
# PYTHON_INCLUDE_DIR and PYTHON_LIBRARY from python3native point to the target sysroot.
PACKAGECONFIG[python] = " \
    -DONNX_BUILD_PYTHON=ON \
    -DPython3_EXECUTABLE=${PYTHON} \
    -DPython3_INCLUDE_DIR=${PYTHON_INCLUDE_DIR} \
    -DPython3_LIBRARY=${PYTHON_LIBRARY}, \
    -DONNX_BUILD_PYTHON=OFF, \
    python3-protobuf-native \
"

do_install:append() {
    # Remove tmpdir references from cmake config — harmful when building against this later
    sed -i '/CMAKE_PREFIX_PATH/d' ${D}${libdir}/cmake/ONNX/ONNXConfig.cmake
    sed -i '/Protobuf_INCLUDE_DIR/d' ${D}${libdir}/cmake/ONNX/ONNXConfig.cmake

    # Install the Python package
    CP_ARGS="-Prf --preserve=mode,timestamps --no-preserve=ownership"
    if ${@bb.utils.contains('PACKAGECONFIG', 'python', 'true', 'false', d)}; then
        install -d ${D}${PYTHON_SITEPACKAGES_DIR}/onnx
        (cd ${S}/onnx; cp --parents $(find . -name "*.py*") ${D}${PYTHON_SITEPACKAGES_DIR}/onnx)
        cp $CP_ARGS ${B}/onnx ${D}${PYTHON_SITEPACKAGES_DIR}

        # nanobind with STABLE_ABI produces onnx_cpp2py_export.abi3.so (no Python version in name)
        so_file=$(find ${B} -maxdepth 3 -name "onnx_cpp2py_export*.so" | head -1)
        if [ -z "${so_file}" ]; then
            bbfatal "onnx_cpp2py_export*.so not found under ${B}"
        fi
        install -m 0755 "${so_file}" ${D}${PYTHON_SITEPACKAGES_DIR}/onnx/

        # Generate version.py — created by setup.py at build time but not in the source tree
        cat > ${D}${PYTHON_SITEPACKAGES_DIR}/onnx/version.py <<EOF
# This file is generated by setup.py. DO NOT EDIT!
version = "${PV}"
git_version = ""
EOF
    fi
}

PACKAGES =+ "python3-${PN}"
FILES:python3-${PN} += "${PYTHON_SITEPACKAGES_DIR}"

# ONNX 1.20.1 removed VERSION/SOVERSION from its cmake targets, so libonnx.so
# and libonnx_proto.so are plain unversioned .so files (not symlinks). Yocto's
# default FILES:${PN}-dev claims ${libdir}/lib*.so and -dev takes priority in
# PACKAGES ordering, causing the dev-elf QA error. Remove the glob from -dev and
# claim the files explicitly in the main package.
FILES:${PN}-dev:remove = "${libdir}/lib*.so"
FILES:${PN} += "${libdir}/libonnx*.so"
RDEPENDS:python3-${PN} += " \
    ${PN} \
    python3-numpy \
    python3-protobuf \
    python3-flatbuffers \
    python3-sympy \
"
